/* Creación de usuario si está trabajando con BD Oracle XE */
CREATE USER MDY3131_ET_FB IDENTIFIED BY "Examen.T2023_FB"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";
ALTER USER MDY3131_ET_FB QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION TO MDY3131_ET_FB;
GRANT "RESOURCE" TO MDY3131_ET_FB;
ALTER USER MDY3131_ET_FB DEFAULT ROLE "RESOURCE";

/* Creación de usuario si está trabajando con BD Oracle Cloud */
CREATE USER MDY3131_ET_FB IDENTIFIED BY "Examen.T2023_FB"
DEFAULT TABLESPACE "DATA"
TEMPORARY TABLESPACE "TEMP";
ALTER USER MDY3131_ET_FB QUOTA UNLIMITED ON DATA;
GRANT CREATE SESSION TO MDY3131_ET_FB;
GRANT "RESOURCE" TO MDY3131_ET_FB;
ALTER USER MDY3131_ET_FB DEFAULT ROLE "RESOURCE";