DECLARE
    V_NUMERO        CLIENTE.NRO_CLIENTE%TYPE;
    V_RUN           VARCHAR2(20):=&RUN;
    V_NOMBRE        VARCHAR2(200);
    V_PROFESION     VARCHAR2(50);
    V_CUMPLE        VARCHAR2(20);
    V_TOTAL         NUMBER;
    V_GIFTCARD      NUMBER;
    V_OBSERVACION   VARCHAR2(200);
    V_NACIMIENTO    DATE;

BEGIN

    SELECT C.NRO_CLIENTE NUMCLIENTE,
        TO_CHAR(C.NUMRUN,'99G999G999')||'-'||C.DVRUN AS RUN,
        C.PNOMBRE||' '||C.SNOMBRE||' '||C.APPATERNO||' '||C.APMATERNO AS NOMBRE,
        P.NOMBRE_PROF_OFIC PROFESION,
        TO_CHAR(C.FECHA_NACIMIENTO,'DD Month') CUMPLE,
        C.FECHA_NACIMIENTO AS FECHANAC,
        SUM(I.MONTO_TOTAL_AHORRADO) TOTAL
    INTO V_NUMERO, V_RUN, V_NOMBRE, V_PROFESION, V_CUMPLE,V_NACIMIENTO, V_TOTAL

    FROM CLIENTE C
        JOIN PROFESION_OFICIO P ON C.COD_PROF_OFIC=P.COD_PROF_OFIC
        JOIN PRODUCTO_INVERSION_CLIENTE I ON C.NRO_CLIENTE=I.NRO_CLIENTE
    WHERE C.NUMRUN=V_RUN
    GROUP BY C.NRO_CLIENTE,TO_CHAR(C.NUMRUN,'99G999G999')||'-'||C.DVRUN,
        C.PNOMBRE||' '||C.SNOMBRE||' '||C.APPATERNO||' '||C.APMATERNO,
        P.NOMBRE_PROF_OFIC,TO_CHAR(C.FECHA_NACIMIENTO,'DD Month'),C.FECHA_NACIMIENTO;
        
    
    IF EXTRACT(MONTH FROM V_NACIMIENTO)=EXTRACT(MONTH FROM SYSDATE)+1 THEN
        V_GIFTCARD:= CASE
                        WHEN V_TOTAL BETWEEN 900001 AND 2000000 THEN 50000
                        WHEN V_TOTAL BETWEEN 2000001 AND 5000000 THEN 100000
                        WHEN V_TOTAL BETWEEN 5000001 AND 8000000 THEN 200000
                        WHEN V_TOTAL BETWEEN 8000001 AND 15000000 THEN 300000
                     END;
        V_OBSERVACION:=NULL;
    ELSE
        V_GIFTCARD:=NULL;
        V_OBSERVACION:='El cliente no está de cumpleaños en el mes procesado';
    END IF;
    
    INSERT INTO CUMPLEANNO_CLIENTE
    VALUES(V_NUMERO, V_RUN, V_NOMBRE, V_PROFESION, V_CUMPLE,V_GIFTCARD,V_OBSERVACION);
END;