-- CASO 1
VARIABLE B_ANNO VARCHAR2(4)
EXEC :B_ANNO:=&ANNO --2023
VARIABLE B_COMUNA VARCHAR2(20)
EXEC :B_COMUNA:=&COMUNA -- 118
VARIABLE B_MOV_ADIC NUMBER
EXEC :B_MOV_ADIC:=&MOV_ADIC -- 25000
VARIABLE B_RUN VARCHAR2(10)
EXEC :B_RUN:=&RUN -- 11846972


DECLARE
V_RUN VARCHAR2(10);
V_DV VARCHAR(1);
V_NOMBRE VARCHAR2(30);
V_SUELDO NUMBER(10);
V_PORCENTAJE NUMBER(2);
V_VALOR NUMBER(5);
BEGIN

   SELECT NUMRUN_EMP AS RUN, DVRUN_EMP AS DV_RUN, PNOMBRE_EMP || ' ' || APPATERNO_EMP || ' ' || APMATERNO_EMP AS NOMBRE_EMP,
    SUELDO_BASE AS SUELDOBASE, TRUNC((SUELDO_BASE / 100000),0) AS PORCENTAJE, SUELDO_BASE*(TRUNC((SUELDO_BASE/100000),0)/100) AS VALOR_NORMAL
    INTO V_RUN,V_DV,V_NOMBRE,V_SUELDO,V_PORCENTAJE,V_VALOR
    FROM EMPLEADO
    WHERE NUMRUN_EMP =:B_RUN AND ID_COMUNA = :B_COMUNA;
    
INSERT INTO proy_movilizacion VALUES(:B_ANNO, V_RUN,V_DV,V_NOMBRE, V_SUELDO, V_PORCENTAJE, V_VALOR, :B_MOV_ADIC, V_VALOR+:B_MOV_ADIC);
END;

SELECT * FROM proy_movilizacion;

 

