-- CASO 2
VAR B_RUN VARCHAR2(10)
EXEC :B_RUN:=12648200;

DECLARE
V_USER USUARIO_CLAVE%ROWTYPE;

V_LETRA_COMUNA VARCHAR2(1);
v_apellido_paterno VARCHAR2(20);
V_E_CIVIL NUMBER(2);
V_ANTIGUEDAD NUMBER(10);
V_MES_ANNO NUMBER(10);
V_RUN NUMBER(9);
V_DV VARCHAR2(1);
V_NOMBRE_EMP VARCHAR2(50);
V_NOMBRE VARCHAR2(20);
V_CLAVE VARCHAR2(50);
BEGIN
    SELECT 
    EXTRACT(MONTH FROM SYSDATE) || '' || EXTRACT(YEAR FROM SYSDATE) AS "MES_ANNO",
    E.NUMRUN_EMP,
    E.DVRUN_EMP,
    E.PNOMBRE_EMP || ' ' || E.SNOMBRE_EMP || ' ' || E.APPATERNO_EMP || ' ' || E.APMATERNO_EMP AS "NOMBRE_EMPLEADO",
    SUBSTR(E.PNOMBRE_EMP,1,3)|| LENGTH(E.PNOMBRE_EMP)||'*'|| SUBSTR(TO_CHAR(E.SUELDO_BASE,'9999999'),-1) ||
    E.DVRUN_EMP || TO_CHAR(EXTRACT(YEAR FROM SYSDATE)-EXTRACT(YEAR FROM E.FECHA_CONTRATO)) AS "NOMBRE_USUARIO",
    SUBSTR(E.NUMRUN_EMP,3,1)||TO_CHAR(TO_NUMBER(TO_CHAR(E.FECHA_NAC,'YYYY'))+2)||TO_CHAR(SUBSTR(E.SUELDO_BASE,-3)-1) AS "CLAVE_USUARIO"
    INTO V_MES_ANNO, V_RUN, V_DV, V_NOMBRE_EMP, V_NOMBRE, V_CLAVE
    FROM EMPLEADO E
    WHERE E.NUMRUN_EMP = :B_RUN;

    SELECT EXTRACT(YEAR FROM SYSDATE)-EXTRACT(YEAR FROM E.FECHA_CONTRATO) 
    INTO V_ANTIGUEDAD FROM EMPLEADO E
    WHERE E.NUMRUN_EMP = :B_RUN;
    
    IF V_ANTIGUEDAD < 10 THEN
        V_NOMBRE:= V_NOMBRE || 'X';
    END IF;
    
    SELECT ID_ESTADO_CIVIL INTO V_E_CIVIL FROM EMPLEADO WHERE numrun_emp = :B_RUN;
    SELECT APPATERNO_EMP INTO v_apellido_paterno FROM EMPLEADO WHERE numrun_emp = :B_RUN;
    
    
    IF v_e_civil = 10 OR v_e_civil = 60 THEN
        V_CLAVE := V_CLAVE || LOWER(SUBSTR(v_apellido_paterno, 1, 2));
    ELSIF v_e_civil = 20 OR v_e_civil = 30 THEN
        V_CLAVE := V_CLAVE || LOWER(SUBSTR(v_apellido_paterno, 1, 1) || SUBSTR(v_apellido_paterno, -1));
    ELSIF v_e_civil = 40 THEN
        V_CLAVE := V_CLAVE || LOWER(SUBSTR(v_apellido_paterno, -3, 1) || SUBSTR(v_apellido_paterno, -2));
    ELSIF v_e_civil = 50 THEN
        V_CLAVE := V_CLAVE || LOWER(SUBSTR(v_apellido_paterno, -2));
    END IF;
    
    
    SELECT SUBSTR(C.NOMBRE_COMUNA,1,1) INTO V_LETRA_COMUNA FROM
    EMPLEADO E JOIN COMUNA C using(ID_COMUNA) WHERE E.NUMRUN_EMP = :B_RUN;
    
    V_CLAVE:= V_CLAVE || TO_CHAR(EXTRACT(MONTH FROM SYSDATE)||EXTRACT(YEAR FROM SYSDATE)) || V_LETRA_COMUNA;
    
    V_USER.MES_ANNO:= V_MES_ANNO;
    V_USER.NUMRUN_EMP:= V_RUN;
    V_USER.DVRUN_EMP:= V_DV;
    V_USER.NOMBRE_EMPLEADO:= V_NOMBRE_EMP;
    V_USER.NOMBRE_USUARIO:= V_NOMBRE;
    V_USER.CLAVE_USUARIO:= V_CLAVE;
    INSERT INTO USUARIO_CLAVE VALUES V_USER;
    
END;

