VAR B_ANNO_PROCESS NUMBER
VAR B_PATENTE VARCHAR2(10);
EXEC :B_ANNO_PROCESS:= 2023;
EXEC :B_PATENTE:= &patente;

DECLARE
V_HIST_CAM HIST_ARRIENDO_ANUAL_CAMION%ROWTYPE;
V_PATENTE VARCHAR2(10);
V_VALOR_ARR NUMBER(10);
V_VALOR_GARAN NUMBER(10);
V_TOTAL_ARR NUMBER(10);

BEGIN
    SELECT 
    NRO_PATENTE, C.VALOR_ARRIENDO_DIA, C.VALOR_GARANTIA_DIA,
    COUNT(AC.ID_ARRIENDO)
    INTO V_PATENTE, V_VALOR_ARR, V_VALOR_GARAN, V_TOTAL_ARR
    FROM CAMION C JOIN ARRIENDO_CAMION AC USING(NRO_PATENTE)
    WHERE EXTRACT(YEAR FROM AC.FECHA_INI_ARRIENDO) = :B_ANNO_PROCESS - 1 AND NRO_PATENTE = :B_PATENTE
    GROUP BY EXTRACT(YEAR FROM SYSDATE) -1, NRO_PATENTE, C.VALOR_ARRIENDO_DIA, C.VALOR_GARANTIA_DIA;
    
    IF V_TOTAL_ARR > 5 THEN
        V_VALOR_ARR:= V_VALOR_ARR - (V_VALOR_ARR * 0.225);
    END IF;
    

    V_HIST_CAM.ANNO_PROCESO := :B_ANNO_PROCESS-1;
    V_HIST_CAM.NRO_PATENTE := V_PATENTE;
    V_HIST_CAM.VALOR_ARRIENDO_DIA := V_VALOR_ARR;
    V_HIST_CAM.VALOR_GARACTIA_DIA := V_VALOR_GARAN;
    V_HIST_CAM.TOTAL_VECES_ARRENDADO := V_TOTAL_ARR;
    
    INSERT INTO HIST_ARRIENDO_ANUAL_CAMION VALUES V_HIST_CAM;
END;

